[book]
title = "ChaosHub"
description = "Empowering SREs to Build Resilient Systems with Controlled Chaos"
authors = ["ChaosHub Team"]
language = "en"
multilingual = false

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Lforlinux/mdbook"
git-repository-icon = "fa fa-github"

